services:
  database:
    image: "mysql:8.2.0-oraclelinux8"
    container_name: exactpro_mysql_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-mysql-exactpro:/var/lib/mysql

  exactpro-app:
    image: diegoneves/exactpro-cmms-backend:latest
    container_name: exactpro-api
    ports:
      - "8080:8080"
      - "8081:5005"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: sh -c "dockerize -wait tcp://$${DB_HOST}:$${DB_PORT} -timeout 20s && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar infrastructure/target/exactpro-cmms.jar"

volumes:
  db-mysql-exactpro:
